services:
  syzkaller:
    build: .
    container_name: syzkaller
    stdin_open: true 
    tty: true
    privileged: true
    working_dir: /syzkaller/gopath/src/github.com/google/syzkaller
    entrypoint: /usr/bin/bash
    environment:
      - HOME=/syzkaller
      - GOPATH=/syzkaller/gopath:/gopath
      - SOURCEDIR=/syzkaller/kernel
    volumes:
      - /home/dwappner/Desktop/linux:/syzkaller/kernel:z
      - /home/dwappner/Desktop/syzkaller:/syzkaller/gopath/src/github.com/google/syzkaller:z
    ports:
      - 8080:56741
    restart: "no"
  syzkaller-client:
    build: ./client
    container_name: syzkaller-client
    stdin_open: true 
    tty: true
    privileged: true
    ports:
      - 3000:3000
    restart: "no"
